services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_USER}/onpk-frontend:${APP_VERSION}
    container_name: onpk-frontend
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"