services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_USER}/onpk-backend:${APP_VERSION}
    container_name: onpk-backend
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"